sudo: required
services:
    - docker

before_install:
    # - docker build -t seanmai/docker-deploy-test -f Dockerfile.dev .
    - docker build -t seanmai/docker-deploy-test .

script:
    - docker run seanmai/docker-deploy-test npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-test"
    env: "DockerTest-env"
    bucket_name: "elasticbeanstalk-us-east-2-515282096087"
    bucket_path: "docker-test"
    on:
        branch: master       # Only deploy on push to master
    accesss_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure:  "$AWS_SECRET_KEY"
