sudo: required
services:
    - docker

before_install:
    - docker build -t seanmai/docker-deploy-test -f Dockerfile.dev .

script:
    - docker run seanmai/docker-deploy-test run test -- --coverage
