sudo: required
services:
    - docker

before_install:
    - docker build -t seanmai/DockerDeployTest -f Dockerfile.dev .

script:
    - docker run seanmai/DockerDeployTest npm run test -- --coverage
